projeto-pet-shop-bd1-2021/Controllers/Animal/AnimalController.cs
using Microsoft.AspNetCore.Mvc;
using projeto_pet_shop_bd1_2021.Repositories;
using projeto_pet_shop_bd1_2021.Models.Animais;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using projeto_pet_shop_bd1_2021.Models.ViewModels;

namespace projeto_pet_shop_bd1_2021.Controllers.AnimalController
{
    public class AnimalController : Controller
    {
        private GenericRepository<Animal> _animalRepository;
        private GenericRepository<Raca> _racaRepository;
        private ClienteRepository _clienteRepository;

        public AnimalController(GenericRepository<Animal> animalRepository, GenericRepository<Raca> racaRepository, ClienteRepository clienteRepository)
        {
            _animalRepository = animalRepository;
            _racaRepository = racaRepository;
            _clienteRepository = clienteRepository;
        }

        #region Views

        public ActionResult Index()
        {
            var model = _animalRepository.GetAll();
            return View(model);
        }

        public ActionResult Details(long id)
        {
            var model = _animalRepository.FindById(id);
            return View(model);
        }

        public ActionResult Create()
        {
            var model = new AnimalViewModel(_racaRepository.GetAll(), _clienteRepository.GetAll());
            return View(model);
        }

        public ActionResult Edit(long id)
        {
            var animal = _animalRepository.FindById(id);
            var racas = _racaRepository.GetAll();
            var clientes = _clienteRepository.GetAll();

            animal.Raca = racas.FirstOrDefault(r => r.Id.Equals(animal.RacaId));
            animal.Cliente = clientes.FirstOrDefault(r => r.Id.Equals(animal.ClienteId));

            var model = new AnimalViewModel(racas, clientes, animal);
            return View(model);
        }

        public ActionResult Delete(long id)
        {
            var model = _animalRepository.FindById(id);
            return View(model);
        }

        #endregion Views

        #region Manipulação de dados

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Animal animal)
        {
            if (ModelState.IsValid)
            {
                _animalRepository.Create(animal);
                return RedirectToAction(nameof(Details), new { id = animal.Id });
            }

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Animal animal)
        {
            if (ModelState.IsValid)
            {
                _animalRepository.Update(animal);
                return RedirectToAction(nameof(Details), new { id = animal.Id });
            }

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(long? id)
        {
            if (id != null)
            {
                _animalRepository.Delete((long)id);
                return RedirectToAction(nameof(Index));
            }

            return View();
        }

        #endregion Manipulação de dados
    }
}

projeto-pet-shop-bd1-2021/Controllers/Animal/RacaController.cs
using Microsoft.AspNetCore.Mvc;
using projeto_pet_shop_bd1_2021.Models.Animais;
using projeto_pet_shop_bd1_2021.Models.ViewModels;
using projeto_pet_shop_bd1_2021.Repositories;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace projeto_pet_shop_bd1_2021.Controllers.AnimalController
{
    public class RacaController : Controller
    {
        private GenericRepository<Raca> _repository;
        private GenericRepository<TipoAnimal> _repositoryTipoAnimal;

        public RacaController(GenericRepository<Raca> repository, GenericRepository<TipoAnimal> repositoryTipoAnimal)
        {
            _repository = repository;
            _repositoryTipoAnimal = repositoryTipoAnimal;
        }

        #region Views

        public ActionResult Index()
        {
            var model = _repository.GetAll();

            foreach (var item in model)
            {
                item.TipoAnimal = _repositoryTipoAnimal.FindById(item.TipoAnimalId);
            }

            return View(model);
        }

        public ActionResult Details(long id)
        {
            var model = _repository.FindById(id);
            model.TipoAnimal = _repositoryTipoAnimal.FindById(model.TipoAnimalId);
            return View(model);
        }

        public ActionResult Create()
        {
            var tiposAnimal = _repositoryTipoAnimal.GetAll();
            var model = new RacaViewModel(tiposAnimal);
            return View(model);
        }

        public ActionResult Edit(long id)
        {
            var raca = _repository.FindById(id);
            var tiposAnimal = _repositoryTipoAnimal.GetAll();
            raca.TipoAnimal = tiposAnimal.FirstOrDefault(r => r.Id.Equals(raca.TipoAnimalId));

            var model = new RacaViewModel(raca, tiposAnimal);

            return View(model);
        }

        public ActionResult Delete(long id)
        {
            var model = _repository.FindById(id);
            return View(model);
        }

        #endregion Views

        #region Manipulação de dados

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Raca raca)
        {
            if (ModelState.IsValid)
            {
                _repository.Create(raca);
                return RedirectToAction(nameof(Details), new { id = raca.Id });
            }

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Raca raca)
        {
            if (ModelState.IsValid)
            {
                _repository.Update(raca);
                return RedirectToAction(nameof(Details), new { id = raca.Id });
            }

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(long? id)
        {
            if (id != null)
            {
                _repository.Delete((long)id);
                return RedirectToAction(nameof(Index));
            }

            return View();
        }

        #endregion Manipulação de dados
    }
}

projeto-pet-shop-bd1-2021/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using projeto_pet_shop_bd1_2021.Models;

namespace projeto_pet_shop_bd1_2021.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Cadastros()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

projeto-pet-shop-bd1-2021/Controllers/Pessoa/ClienteController.cs
using Microsoft.AspNetCore.Mvc;
using projeto_pet_shop_bd1_2021.Models;
using projeto_pet_shop_bd1_2021.Models.Pessoas;
using projeto_pet_shop_bd1_2021.Models.ViewModels;
using projeto_pet_shop_bd1_2021.Repositories;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace projeto_pet_shop_bd1_2021.Controllers
{
    public class ClienteController : Controller
    {
        private ClienteRepository _clienteRepository;
        private PessoaRepository _pessoaRepository;

        public ClienteController(ClienteRepository clienteRepository, PessoaRepository pessoaRepository)
        {
            _clienteRepository = clienteRepository;
            _pessoaRepository = pessoaRepository;
        }

        #region Views

        public IActionResult Index()
        {
            var model = _clienteRepository.GetAll();
            return View(model);
        }

        public IActionResult Create()
        {
            return View(new ClienteViewModel(_pessoaRepository.GetAll()));
        }

        public IActionResult Details(long id)
        {
            var model = _clienteRepository.FindById(id);
            return View(model);
        }

        public IActionResult Edit(long id)
        {
            var model = _clienteRepository.FindById(id);
            return View(model);
        }

        public IActionResult Delete(long id)
        {
            var model = _clienteRepository.FindById(id);
            return View(model);
        }

        #endregion Views

        #region Manipulação de dados

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Cliente cliente)
        {
            if (ModelState.IsValid)
            {
                if (_pessoaRepository.Exists(cliente.PessoaId))
                {
                    if (_clienteRepository.Exists(cliente.PessoaId))
                    {
                        return RedirectToAction(nameof(Index), "Error", new ErrorViewModel("ID da pessoa já cadastrado como cliente."));
                    }

                    _clienteRepository.Create(cliente);
                    return RedirectToAction(nameof(Details), new { id = cliente.PessoaId });
                }
                else
                {
                    return RedirectToAction(nameof(Index), "Error", new ErrorViewModel("ID da pessoa não existe."));
                }
            }

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Cliente cliente)
        {
            if (ModelState.IsValid)
            {
                _clienteRepository.Update(cliente);
                return RedirectToAction(nameof(Details), new { id = cliente.PessoaId });
            }

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(long? id)
        {
            if (id != null)
            {
                _clienteRepository.Delete((long)id);
                return RedirectToAction(nameof(Index));
            }

            return View();
        }

        #endregion Manipulação de dados
    }
}

projeto-pet-shop-bd1-2021/Controllers/Pessoa/PessoaController.cs
using Microsoft.AspNetCore.Mvc;
using projeto_pet_shop_bd1_2021.Models.Pessoas;
using projeto_pet_shop_bd1_2021.Repositories;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace projeto_pet_shop_bd1_2021.Controllers
{
    public class PessoaController : Controller
    {
        private PessoaRepository _repository;

        public PessoaController(PessoaRepository repository)
        {
            _repository = repository;
        }

        #region Views

        public IActionResult Index()
        {
            var model = _repository.GetAll();
            return View(model);
        }
        
        public IActionResult Create()
        {
            return View();
        }
        
        public IActionResult Details(long id)
        {
            var model = _repository.FindById(id);
            return View(model);
        }
        
        public IActionResult Edit(long id)
        {
            var model = _repository.FindById(id);
            return View(model);
        }
        
        public IActionResult Delete(long id)
        {
            var model = _repository.FindById(id);
            return View(model);
        }

        #endregion Views

        #region Manipulação de dados

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Pessoa pessoa)
        {
            if (ModelState.IsValid)
            {
                _repository.Create(pessoa);
                return RedirectToAction(nameof(Details), new { id = pessoa.Id });
            }

            return View();
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Pessoa pessoa)
        {
            if (ModelState.IsValid)
            {
                _repository.Update(pessoa);
                return RedirectToAction(nameof(Details), new { id = pessoa.Id });
            }

            return View();
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(long? id)
        {
            if (id != null)
            {
                _repository.Delete((long)id);
                return RedirectToAction(nameof(Index));
            }

            return View();
        }

        #endregion Manipulação de dados
    }
}

projeto-pet-shop-bd1-2021/Views/Home/Cadastros.cshtml
@{
    ViewData["Title"] = "Cadastros";
}
<h1>@ViewData["Title"]</h1>

<div class="col-md-12">
    <div class="row">
        <div class="col-md-3">
            <a asp-controller="Pessoa" asp-action="Index">
                <input type="button" value="Listar Pessoas" class="btn btn-primary" />
            </a>
        </div>
        <div class="col-md-3">
            <a asp-controller="Pessoa" asp-action="Create">
                <input type="button" value="Cadastrar Pessoa" class="btn btn-primary" />
            </a>
        </div>
    </div>
    <br />
    <div class="row">
        <div class="col-md-3">
            <a asp-controller="Cliente" asp-action="Index">
                <input type="button" value="Listar Clientes" class="btn btn-primary" />
            </a>
        </div>
        <div class="col-md-3">
            <a asp-controller="Cliente" asp-action="Create">
                <input type="button" value="Cadastrar Cliente" class="btn btn-primary" />
            </a>
        </div>
    </div>
    <br />
    <div class="row">
        <div class="col-md-3">
            <a asp-controller="Funcionario" asp-action="Index">
                <input type="button" value="Listar Funcionarios" class="btn btn-primary" />
            </a>
        </div>
        <div class="col-md-3">
            <a asp-controller="Funcionario" asp-action="Create">
                <input type="button" value="Cadastrar Funcionario" class="btn btn-primary" />
            </a>
        </div>
    </div>
    <br />
    <div class="row">
        <div class="col-md-3">
            <a asp-controller="Animal" asp-action="Index">
                <input type="button" value="Listar animais" class="btn btn-primary" />
            </a>
        </div>
        <div class="col-md-3">
            <a asp-controller="Animal" asp-action="Create">
                <input type="button" value="Cadastrar animal" class="btn btn-primary" />
            </a>
        </div>
    </div>
    <br />
    <div class="row">
        <div class="col-md-3">
            <a asp-controller="Atendimento" asp-action="Index">
                <input type="button" value="Listar Atendimentos" class="btn btn-primary" />
            </a>
        </div>
        <div class="col-md-3">
            <a asp-controller="Atendimento" asp-action="Create">
                <input type="button" value="Cadastrar Atendimento" class="btn btn-primary" />
            </a>
        </div>
    </div>
    <br />
    <div class="row">
        <div class="col-md-3">
            <a asp-controller="TipoAnimal" asp-action="Index">
                <input type="button" value="Listar tipos de animais" class="btn btn-primary" />
            </a>
        </div>
        <div class="col-md-3">
            <a asp-controller="TipoAnimal" asp-action="Create">
                <input type="button" value="Cadastrar tipo animal" class="btn btn-primary" />
            </a>
        </div>
    </div>
    <br />
    <div class="row">
        <div class="col-md-3">
            <a asp-controller="Raca" asp-action="Index">
                <input type="button" value="Listar racas" class="btn btn-primary" />
            </a>
        </div>
        <div class="col-md-3">
            <a asp-controller="Raca" asp-action="Create">
                <input type="button" value="Cadastrar raca" class="btn btn-primary" />
            </a>
        </div>
    </div>
    <br />
    <div class="row">
        <div class="col-md-3">
            <a asp-controller="Servico" asp-action="Index">
                <input type="button" value="Listar servicos" class="btn btn-primary" />
            </a>
        </div>
        <div class="col-md-3">
            <a asp-controller="Servico" asp-action="Create">
                <input type="button" value="Cadastrar servico" class="btn btn-primary" />
            </a>
        </div>
    </div>
</div>

projeto-pet-shop-bd1-2021/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Projeto de BD 1</h1>
    <p>Desenvolvido por: </p>
    <p>Leonardo Silvatti</p>
    <p>Guilherme Alves</p>
    <p>Matheus Polato</p>
</div>